version: '2.1'

services:
  api:
    image: oam-api
    build: .
    environment:
      - DATABASE_URL=postgresql://openaerialmap:openaerialmap@postgresql/openaerialmap_development
    ports:
      - 3000:3000
  postgresql:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=openaerialmap
      - POSTGRES_PASSWORD=openaerialmap
      - POSTGRES_DB=openaerialmap_development
    volumes:
     - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: